apply plugin: 'com.android.library'

group = 'expo.modules.alarmring'

def safeExtGet(name, fallback) {
  if (rootProject.ext.has(name)) {
    return rootProject.ext.get(name)
  }
  return fallback
}

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "alarm.ring"
  compileSdkVersion safeExtGet("compileSdkVersion", 36)

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
  }

  publishing {
    singleVariant("release") {
      withSourcesJar()
    }
  }
}
